/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.marmitao.view;

import br.com.marmitao.Control.EncomendaPresencialControl;
import br.com.marmitao.model.RelogioThread;

/**
 *
 * @author Bruno
 */
public class GerenciarEncomendaPresencial extends javax.swing.JInternalFrame {

    private EncomendaPresencialControl encoPresencialControl;

    /**
     * Creates new form GerenciarEncomendaPresencial
     */
    public GerenciarEncomendaPresencial() {
        initComponents();
        RelogioThread rt = new RelogioThread(lblDataPedido);
        rt.iniciarRelogio();
        encoPresencialControl = new EncomendaPresencialControl(cbCliente, lblDataPedido, tfDataEntrega, tfPesquisa,
                tabelaEncomendaPresencial);
        encoPresencialControl.popularComboBox();
        encoPresencialControl.listarEncomendaPresencial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblDataPedido = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfDataEntrega = new javax.swing.JTextField();
        cbCliente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfPesquisa = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data;
            data = new javax.swing.text.MaskFormatter("##/##/####");
            tfDataEntrega = new javax.swing.JFormattedTextField(data);

        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEncomendaPresencial = new javax.swing.JTable();
        btExcluir = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btReceberEncomenda = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Encomenda Presencial");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerenciar Encomenda Presencial");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Data Pedido: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        lblDataPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(lblDataPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 208, 17));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Data Entrega:  ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        getContentPane().add(tfDataEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 199, -1));

        cbCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbClienteMousePressed(evt);
            }
        });
        getContentPane().add(cbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 385, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Cliente: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Pesquisar: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, -1));

        tfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPesquisaKeyReleased(evt);
            }
        });
        getContentPane().add(tfPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 199, -1));

        tabelaEncomendaPresencial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Data Pedido", "Data Entrega", "Status"
            }
        ));
        jScrollPane1.setViewportView(tabelaEncomendaPresencial);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 620, 230));

        btExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 80, 30));

        btSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 100, 30));

        btEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 80, 30));

        btReceberEncomenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btReceberEncomenda.setText("Receber encomenda");
        btReceberEncomenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btReceberEncomendaMouseClicked(evt);
            }
        });
        getContentPane().add(btReceberEncomenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 160, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbClienteMousePressed
    }//GEN-LAST:event_cbClienteMousePressed

    private void tfPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisaKeyReleased
        encoPresencialControl.pequisarEncomendaPresencialAction();
    }//GEN-LAST:event_tfPesquisaKeyReleased

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        encoPresencialControl.excluirEncomendaPresencialAction();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        encoPresencialControl.salvarEncomendaPresencialAction();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        encoPresencialControl.setarCamposEncomendaPresencial();
    }//GEN-LAST:event_btEditarActionPerformed

    private void btReceberEncomendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btReceberEncomendaMouseClicked
        encoPresencialControl.alterarStatusRecebido();
    }//GEN-LAST:event_btReceberEncomendaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btReceberEncomenda;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDataPedido;
    private javax.swing.JTable tabelaEncomendaPresencial;
    private javax.swing.JTextField tfDataEntrega;
    private javax.swing.JTextField tfPesquisa;
    // End of variables declaration//GEN-END:variables
}
