/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.marmitao.view;

import br.com.marmitao.Control.EncomendaControl;
import br.com.marmitao.model.RelogioThread;

/**
 *
 * @author Bruno
 */
public class GerenciarEncomenda extends javax.swing.JInternalFrame {

    private EncomendaControl encomendaControl;

    /**
     * Creates new form GerenciarEncomenda
     */
    public GerenciarEncomenda() {
        initComponents();
        RelogioThread rt = new RelogioThread(lblDataPedido);
        rt.iniciarRelogio();
        encomendaControl = new EncomendaControl(cbCliente, cbEndereco, cbEntregador, lblDataPedido,
                tfDataEntrega, tfPesquisa, tabelaEncomenda);
        encomendaControl.popularComboBox();
        encomendaControl.listarEncomenda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox<>();
        cbEntregador = new javax.swing.JComboBox<>();
        tfDataEntrega = new javax.swing.JTextField();
        cbEndereco = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEncomenda = new javax.swing.JTable();
        btExcluir = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btEnviarEncomenda = new javax.swing.JButton();
        btReceberEncomenda = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfPesquisa = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data;
            data = new javax.swing.text.MaskFormatter("##/##/####");
            tfDataEntrega = new javax.swing.JFormattedTextField(data);

        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        lblDataPedido = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Encomenda");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerenciar Encomenda");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Cliente: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Entregador: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Data Pedido: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Data Entrega:  ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        cbCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbClienteItemStateChanged(evt);
            }
        });
        cbCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbClienteMousePressed(evt);
            }
        });
        getContentPane().add(cbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 385, -1));

        getContentPane().add(cbEntregador, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 350, -1));
        getContentPane().add(tfDataEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 110, -1));

        getContentPane().add(cbEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 360, -1));

        tabelaEncomenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Endereco", "CEP", "Entregador", "Data Pedido", "Data Entrega", "Status"
            }
        ));
        jScrollPane1.setViewportView(tabelaEncomenda);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 620, 250));

        btExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 170, 80, 30));

        btSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 100, 30));

        btEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 80, 30));

        btEnviarEncomenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btEnviarEncomenda.setText("Enviar encomenda");
        btEnviarEncomenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarEncomendaActionPerformed(evt);
            }
        });
        getContentPane().add(btEnviarEncomenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 160, 40));

        btReceberEncomenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btReceberEncomenda.setText("Receber encomenda");
        btReceberEncomenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReceberEncomendaActionPerformed(evt);
            }
        });
        getContentPane().add(btReceberEncomenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, 160, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Endereço: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Pesquisar: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, -1, -1));

        tfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPesquisaKeyReleased(evt);
            }
        });
        getContentPane().add(tfPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 199, -1));

        lblDataPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(lblDataPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 208, 17));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbClienteMousePressed
    }//GEN-LAST:event_cbClienteMousePressed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        encomendaControl.salvarEncomendaAction();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        encomendaControl.setarCamposEncomenda();
    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        encomendaControl.excluirEncomendaAction();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btEnviarEncomendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarEncomendaActionPerformed
        encomendaControl.alterarStatusEnviado();
    }//GEN-LAST:event_btEnviarEncomendaActionPerformed

    private void btReceberEncomendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReceberEncomendaActionPerformed
        encomendaControl.alterarStatusRecebido();
    }//GEN-LAST:event_btReceberEncomendaActionPerformed

    private void tfPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisaKeyReleased
        encomendaControl.pequisarEncomendaAction();
    }//GEN-LAST:event_tfPesquisaKeyReleased

    private void cbClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbClienteItemStateChanged
       encomendaControl.popularEnderecoComboBox();
    }//GEN-LAST:event_cbClienteItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btEnviarEncomenda;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btReceberEncomenda;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JComboBox<String> cbEndereco;
    private javax.swing.JComboBox<String> cbEntregador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDataPedido;
    private javax.swing.JTable tabelaEncomenda;
    private javax.swing.JTextField tfDataEntrega;
    private javax.swing.JTextField tfPesquisa;
    // End of variables declaration//GEN-END:variables
}
