/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.marmitao.view;

import br.com.marmitao.Control.EncomendaProdutoControl;
import javax.swing.JOptionPane;

/**
 *
 * @author Bruno
 */
public class ProdutosEncomenda extends javax.swing.JInternalFrame {

    private EncomendaProdutoControl encoProdutoControl;

    /**
     * Creates new form ProdutosEncomenda
     */
    public ProdutosEncomenda() {
        initComponents();
        encoProdutoControl = new EncomendaProdutoControl(cbEncomenda, cbProduto, lblValorTotalPedidos, tfQuantidade,
                tfValor, tabelaEncomendaProduto);
        encoProdutoControl.popularComboBox();
        encoProdutoControl.listarVinculoEncomendaProduto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEncomendaProduto = new javax.swing.JTable();
        cbEncomenda = new javax.swing.JComboBox<>();
        cbProduto = new javax.swing.JComboBox<>();
        tfQuantidade = new javax.swing.JTextField();
        tfValor = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btCartaoPedido = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblValorTotalPedidos = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Produtos Encomenda");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Produtos Encomenda");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Encomenda: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Produto: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Quantidade: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Valor: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        tabelaEncomendaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Encomenda", "Logradouro", "Produto", "Valor Produto", "Quantidade", "Valor Pedido"
            }
        ));
        jScrollPane1.setViewportView(tabelaEncomendaProduto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 700, 208));

        cbEncomenda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEncomendaItemStateChanged(evt);
            }
        });
        getContentPane().add(cbEncomenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 480, -1));

        getContentPane().add(cbProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 320, -1));

        tfQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfQuantidadeKeyReleased(evt);
            }
        });
        getContentPane().add(tfQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 90, -1));

        tfValor.setEditable(false);
        getContentPane().add(tfValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 70, -1));

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 101, 32));

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 86, 32));

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 89, 32));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Valor Total Pedidos: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, -1, -1));

        btCartaoPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btCartaoPedido.setText("Cartão de Pedido");
        btCartaoPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCartaoPedidoMouseClicked(evt);
            }
        });
        btCartaoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCartaoPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btCartaoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 160, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Clique no botão abaixo para imprimir os dados do pedido selecionado!! ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, -1, -1));

        lblValorTotalPedidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(lblValorTotalPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 150, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQuantidadeKeyReleased
        encoProdutoControl.popularTFValor();
    }//GEN-LAST:event_tfQuantidadeKeyReleased

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        encoProdutoControl.salvarEncomendaProdutoAction();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        encoProdutoControl.setarCamposEncomenda();
    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        encoProdutoControl.excluirEncomendaAction();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btCartaoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCartaoPedidoActionPerformed
        encoProdutoControl.cartãoEncomenda();
    }//GEN-LAST:event_btCartaoPedidoActionPerformed

    private void btCartaoPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCartaoPedidoMouseClicked
        JOptionPane.showMessageDialog(null, encoProdutoControl.encomendaProdutoSelecionada().toString());
    }//GEN-LAST:event_btCartaoPedidoMouseClicked

    private void cbEncomendaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEncomendaItemStateChanged
       encoProdutoControl.listarVinculoEncomendaProduto();
    }//GEN-LAST:event_cbEncomendaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCartaoPedido;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> cbEncomenda;
    private javax.swing.JComboBox<String> cbProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblValorTotalPedidos;
    private javax.swing.JTable tabelaEncomendaProduto;
    private javax.swing.JTextField tfQuantidade;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
